### ISSUE TITLE
Hi, How to download your MobileFaceNet model

### ISSUE THREAD

**Issue by onexuan** [shangleyi/insightface-training-note#1]
Hi, How to download your MobileFaceNet(triplet, Arc) model?

**Comment by shangleyi** [comment]
Sorry, the model belongs to the company I worked with so I can't post them publicly. However I posted the training process, and we have an assumption that the model's high accuracy is due to noises in the first process. The training pipelines are also provided in my note. Maybe you can try to train a new model in that way. Sorry again.

**Comment by onexuan** [comment]
I get it, I will try training process.

**Comment by onexuan** [comment]
How size your MobileFaceNet(triplet, Arc) model?

**Comment by shangleyi** [comment]
My model's size was about 3.9MB.

**Comment by onexuan** [comment]
OK, Thanks!

**Comment by luluvi** [comment]
Hello，can you share the agedb-30 datasets?  thank you!
